spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:consultorio
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
api:
  basePath: /api/v1